const ROLES = {
  ADMIN: 'ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  CHIEF_SECRETARY: 'CHIEF_SECRETARY',
  HOD: 'HOD',
  FACULTY: 'FACULTY',
  STUDENT: 'STUDENT',
  EXTERNAL: 'EXTERNAL',
  EXTERNAL_STAFF: 'EXTERNAL_STAFF',
  FIRST_YEAR_COORDINATOR: 'FIRST_YEAR_COORDINATOR',
};

const SUBJECT_TYPES = {
  THEORY: 'THEORY',
  LAB: 'LAB',
  INTEGRATED: 'INTEGRATED',
};

const ATTENDANCE_THRESHOLDS = {
  ELIGIBLE: 75,
  CONDONATION_MIN: 65,
  CONDONATION_MAX: 74,
};

const GRADE_POINTS = {
  'O': 10, 'A+': 9, 'A': 8,
  'B+': 7, 'B': 6, 'C': 5, 'U': 0, 'UA': 0,
};

const PASS_MARKS = {
  TOTAL_MIN: 50,
  THEORY_EXTERNAL_MIN: 27,
  LAB_EXTERNAL_MIN: 18,
  INTEGRATED_EXTERNAL_MIN: 22.5,
};

const STUDENT_CATEGORIES = {
  FIRST_YEAR: 'FIRST_YEAR',
  DEPARTMENT: 'DEPARTMENT',
  PASSED_OUT: 'PASSED_OUT',
  ARREAR: 'ARREAR',
};

const ELIGIBILITY_STATUS = {
  ELIGIBLE: 'ELIGIBLE',
  CONDONATION: 'CONDONATION',
  DETAINED: 'DETAINED',
};

const REGULATION_DEFAULT = '2021';

module.exports = {
  ROLES,
  SUBJECT_TYPES,
  ATTENDANCE_THRESHOLDS,
  GRADE_POINTS,
  PASS_MARKS,
  STUDENT_CATEGORIES,
  ELIGIBILITY_STATUS,
  REGULATION_DEFAULT
};
