import api from './api.js'
export const getSystemUsers = () => api.get('/admin/users')
export const createSystemUser = (data) => api.post('/admin/users', data)
export const resetSystemUserPassword = (id, data) => api.patch(`/admin/users/${id}/reset-password`, data)
export const toggleUserStatus = (id, data) => api.patch(`/admin/users/${id}/status`, data)
export const deleteSystemUser = (id) => api.delete(`/admin/users/${id}`)
export const getActivityLogs = (params) => api.get('/admin/settings/activity-logs', { params })
export const passOutStudents = (data) => api.post('/admin/students/pass-out', data)
export const getDepartments = () => api.get('/admin/departments')
export const getSections = () => api.get('/admin/sections')
export const getDashboardStats = () => api.get('/admin/stats')
export const getSystemSettings = () => api.get('/admin/settings')
export const updateSystemSetting = (data) => api.post('/admin/settings/update', data)
